---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflareSync.secretName }}
type: Opaque
data:
  email: {{ .Values.cloudflareSync.cloudflareEmail }}
  token: {{ .Values.cloudflareSync.cloudflareApiKey }}
