---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.cloudflareSync.serviceAccount }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.cloudflareSync.serviceAccount }}-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.cloudflareSync.serviceAccount }} 
subjects:
- kind: ServiceAccount
  name: {{ .Values.cloudflareSync.serviceAccount }} 
  namespace: default
